services:
  nextjs:
    container_name: nextjs_app
    image: food-delivery-application
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - dev
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/food-delivery
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=300
      - WATCHPACK_POLLING=true
    command: npm run dev
    depends_on:
      - mongodb

  # mongodb
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - dev
    volumes:
      - mongodb_data:/data/db

  # mongo-express
  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    ports:
      - "9090:8081"
    networks:
      - dev
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    depends_on:
      - mongodb

networks:
  dev:
    driver: bridge

volumes:
  mongodb_data:
