services:
  nextjs:
    container_name: nextjs_app
    image: food-delivery-application
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules 
    environment:
      - NODE_ENV=development
